# Generated by Django 5.1.7 on 2025-04-03 01:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_auth', '0003_admin_alter_myuser_role'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='admin',
            options={'verbose_name': 'Admin', 'verbose_name_plural': 'Admins'},
        ),
        migrations.AlterModelOptions(
            name='customer',
            options={'verbose_name': 'Customer', 'verbose_name_plural': 'Customers'},
        ),
        migrations.AlterModelOptions(
            name='manager',
            options={'verbose_name': 'Manager', 'verbose_name_plural': 'Managers'},
        ),
        migrations.AlterModelOptions(
            name='myuser',
            options={'verbose_name': 'MyUser', 'verbose_name_plural': 'MyUsers'},
        ),
    ]
